// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: wind_instruments

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ScreenMain, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_ScreenMain);

    ui_MainContainerWind = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_MainContainerWind);
    lv_obj_set_width(ui_MainContainerWind, lv_pct(100));
    lv_obj_set_height(ui_MainContainerWind, lv_pct(100));
    lv_obj_set_align(ui_MainContainerWind, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_MainContainerWind, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainContainerWind, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainContainerWind, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainContainerWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNavigation = lv_obj_create(ui_MainContainerWind);
    lv_obj_set_height(ui_PanelNavigation, 50);
    lv_obj_set_width(ui_PanelNavigation, lv_pct(100));
    lv_obj_set_align(ui_PanelNavigation, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelNavigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNavigation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNavigation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelNavigation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindScreen = lv_label_create(ui_PanelNavigation);
    lv_obj_set_width(ui_LabelWindScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWindScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindScreen, "Wind");
    lv_obj_set_style_text_color(ui_LabelWindScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindScreen, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_PanelNavigation);
    lv_obj_set_width(ui_Button3, 80);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 20);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_set_align(ui_Button3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_1551684850, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWindGauge = lv_obj_create(ui_MainContainerWind);
    lv_obj_set_width(ui_PanelWindGauge, 320);
    lv_obj_set_height(ui_PanelWindGauge, 320);
    lv_obj_set_x(ui_PanelWindGauge, 0);
    lv_obj_set_y(ui_PanelWindGauge, 50);
    lv_obj_clear_flag(ui_PanelWindGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWindGauge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWindGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWindGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelWindGauge, &ui_img_scale_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWindGauge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAppWindSpd = lv_label_create(ui_PanelWindGauge);
    lv_obj_set_width(ui_LabelAppWindSpd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAppWindSpd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAppWindSpd, -9);
    lv_obj_set_y(ui_LabelAppWindSpd, 68);
    lv_obj_set_align(ui_LabelAppWindSpd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAppWindSpd, "00.0");
    lv_obj_set_style_text_color(ui_LabelAppWindSpd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAppWindSpd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAppWindSpd, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAppWindSpd, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArrowTrue = lv_img_create(ui_PanelWindGauge);
    lv_img_set_src(ui_ImageArrowTrue, &ui_img_arrow_true_png);
    lv_obj_set_width(ui_ImageArrowTrue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArrowTrue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageArrowTrue, 0);
    lv_obj_set_y(ui_ImageArrowTrue, -130);
    lv_obj_set_align(ui_ImageArrowTrue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageArrowTrue, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageArrowTrue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageArrowTrue, 8, 148);

    ui_ImageArrowApp = lv_img_create(ui_PanelWindGauge);
    lv_img_set_src(ui_ImageArrowApp, &ui_img_arrow_app_png);
    lv_obj_set_width(ui_ImageArrowApp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArrowApp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageArrowApp, 0);
    lv_obj_set_y(ui_ImageArrowApp, -80);
    lv_obj_set_align(ui_ImageArrowApp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageArrowApp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageArrowApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageArrowApp, 8, 123);

    ui_ContainerTWS = lv_obj_create(ui_MainContainerWind);
    lv_obj_remove_style_all(ui_ContainerTWS);
    lv_obj_set_width(ui_ContainerTWS, 121);
    lv_obj_set_height(ui_ContainerTWS, 64);
    lv_obj_set_x(ui_ContainerTWS, 8);
    lv_obj_set_y(ui_ContainerTWS, 345);
    lv_obj_clear_flag(ui_ContainerTWS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1TWS = lv_label_create(ui_ContainerTWS);
    lv_obj_set_width(ui_Label1TWS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1TWS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1TWS, 10);
    lv_obj_set_y(ui_Label1TWS, 0);
    lv_label_set_text(ui_Label1TWS, "TWS");
    lv_obj_set_style_text_color(ui_Label1TWS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1TWS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1TWS, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_ContainerTWS);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 2);
    lv_obj_set_x(ui_Panel1, 10);
    lv_obj_set_y(ui_Panel1, 25);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWSValue = lv_label_create(ui_ContainerTWS);
    lv_obj_set_width(ui_LabelTWSValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWSValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWSValue, -35);
    lv_obj_set_y(ui_LabelTWSValue, 15);
    lv_obj_set_align(ui_LabelTWSValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTWSValue, "00.0");
    lv_obj_set_style_text_color(ui_LabelTWSValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWSValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWSValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ContainerTWS);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 43);
    lv_obj_set_y(ui_Label2, 18);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "k\nt");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTWD = lv_obj_create(ui_MainContainerWind);
    lv_obj_remove_style_all(ui_ContainerTWD);
    lv_obj_set_width(ui_ContainerTWD, 121);
    lv_obj_set_height(ui_ContainerTWD, 64);
    lv_obj_set_x(ui_ContainerTWD, 196);
    lv_obj_set_y(ui_ContainerTWD, 345);
    lv_obj_clear_flag(ui_ContainerTWD, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWD = lv_label_create(ui_ContainerTWD);
    lv_obj_set_width(ui_LabelTWD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWD, -14);
    lv_obj_set_y(ui_LabelTWD, 0);
    lv_obj_set_align(ui_LabelTWD, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTWD, "TWD");
    lv_obj_set_style_text_color(ui_LabelTWD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWD, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_ContainerTWD);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 2);
    lv_obj_set_x(ui_Panel4, 10);
    lv_obj_set_y(ui_Panel4, 25);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWDValue = lv_label_create(ui_ContainerTWD);
    lv_obj_set_width(ui_LabelTWDValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWDValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWDValue, -35);
    lv_obj_set_y(ui_LabelTWDValue, 15);
    lv_obj_set_align(ui_LabelTWDValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTWDValue, "000");
    lv_obj_set_style_text_color(ui_LabelTWDValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWDValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWDValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ContainerTWD);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 34);
    lv_obj_set_y(ui_Label4, 6);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "o");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerAWA = lv_obj_create(ui_MainContainerWind);
    lv_obj_remove_style_all(ui_ContainerAWA);
    lv_obj_set_width(ui_ContainerAWA, 121);
    lv_obj_set_height(ui_ContainerAWA, 64);
    lv_obj_set_x(ui_ContainerAWA, 8);
    lv_obj_set_y(ui_ContainerAWA, 413);
    lv_obj_clear_flag(ui_ContainerAWA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAWA = lv_label_create(ui_ContainerAWA);
    lv_obj_set_width(ui_LabelAWA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAWA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAWA, 16);
    lv_obj_set_y(ui_LabelAWA, 4);
    lv_label_set_text(ui_LabelAWA, "AWA");
    lv_obj_set_style_text_color(ui_LabelAWA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAWA, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelAWA, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelAWA, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelAWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelAWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelAWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelAWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelAWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ContainerAWA);
    lv_obj_set_width(ui_Panel3, 100);
    lv_obj_set_height(ui_Panel3, 2);
    lv_obj_set_x(ui_Panel3, 10);
    lv_obj_set_y(ui_Panel3, 33);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAWAValue = lv_label_create(ui_ContainerAWA);
    lv_obj_set_width(ui_LabelAWAValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAWAValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAWAValue, -35);
    lv_obj_set_y(ui_LabelAWAValue, 17);
    lv_obj_set_align(ui_LabelAWAValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelAWAValue, "000");
    lv_obj_set_style_text_color(ui_LabelAWAValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAWAValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAWAValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ContainerAWA);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 34);
    lv_obj_set_y(ui_Label3, 6);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "o");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTWA = lv_obj_create(ui_MainContainerWind);
    lv_obj_remove_style_all(ui_ContainerTWA);
    lv_obj_set_width(ui_ContainerTWA, 121);
    lv_obj_set_height(ui_ContainerTWA, 64);
    lv_obj_set_x(ui_ContainerTWA, 196);
    lv_obj_set_y(ui_ContainerTWA, 413);
    lv_obj_clear_flag(ui_ContainerTWA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1TWA = lv_label_create(ui_ContainerTWA);
    lv_obj_set_width(ui_Label1TWA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1TWA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1TWA, 16);
    lv_obj_set_y(ui_Label1TWA, 4);
    lv_label_set_text(ui_Label1TWA, "TWA");
    lv_obj_set_style_text_color(ui_Label1TWA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1TWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1TWA, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label1TWA, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1TWA, lv_color_hex(0xFFFD18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1TWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label1TWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1TWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1TWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1TWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_ContainerTWA);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 2);
    lv_obj_set_x(ui_Panel2, 10);
    lv_obj_set_y(ui_Panel2, 33);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWAValue = lv_label_create(ui_ContainerTWA);
    lv_obj_set_width(ui_LabelTWAValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWAValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWAValue, -35);
    lv_obj_set_y(ui_LabelTWAValue, 17);
    lv_obj_set_align(ui_LabelTWAValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTWAValue, "000");
    lv_obj_set_style_text_color(ui_LabelTWAValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWAValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWAValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ContainerTWA);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 34);
    lv_obj_set_y(ui_Label1, 6);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "o");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainContainerCompass = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_MainContainerCompass);
    lv_obj_set_width(ui_MainContainerCompass, lv_pct(100));
    lv_obj_set_height(ui_MainContainerCompass, lv_pct(100));
    lv_obj_add_flag(ui_MainContainerCompass, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainContainerCompass, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainContainerCompass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainContainerCompass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNavigation2 = lv_obj_create(ui_MainContainerCompass);
    lv_obj_set_height(ui_PanelNavigation2, 50);
    lv_obj_set_width(ui_PanelNavigation2, lv_pct(100));
    lv_obj_set_align(ui_PanelNavigation2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelNavigation2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNavigation2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNavigation2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelNavigation2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindScreen2 = lv_label_create(ui_PanelNavigation2);
    lv_obj_set_width(ui_LabelWindScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWindScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindScreen2, "Compass");
    lv_obj_set_style_text_color(ui_LabelWindScreen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindScreen2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_PanelNavigation2);
    lv_obj_set_width(ui_Button5, 80);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -20);
    lv_obj_set_y(ui_Button5, 0);
    lv_obj_set_align(ui_Button5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button5, &ui_img_674587949, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_PanelNavigation2);
    lv_obj_set_width(ui_Button1, 80);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 20);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_1551684850, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCompassBack = lv_img_create(ui_MainContainerCompass);
    lv_img_set_src(ui_ImageCompassBack, &ui_img_827446305);
    lv_obj_set_width(ui_ImageCompassBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCompassBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCompassBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCompassBack, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCompassBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageRedGreen = lv_img_create(ui_MainContainerCompass);
    lv_img_set_src(ui_ImageRedGreen, &ui_img_1213530082);
    lv_obj_set_width(ui_ImageRedGreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRedGreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageRedGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRedGreen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRedGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCompassCenter = lv_img_create(ui_MainContainerCompass);
    lv_img_set_src(ui_ImageCompassCenter, &ui_img_1486399645);
    lv_obj_set_width(ui_ImageCompassCenter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCompassCenter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCompassCenter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCompassCenter, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCompassCenter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCompasHeading = lv_label_create(ui_MainContainerCompass);
    lv_obj_set_width(ui_LabelCompasHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCompasHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCompasHeading, 0);
    lv_obj_set_y(ui_LabelCompasHeading, -92);
    lv_obj_set_align(ui_LabelCompasHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCompasHeading, "000");
    lv_obj_set_style_text_align(ui_LabelCompasHeading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCompasHeading, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_MainContainerCompass);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -59);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Depth (m)");

    ui_Label10 = lv_label_create(ui_MainContainerCompass);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 15);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "GPS speed (kt)");

    ui_LabelCompGPSSpeed = lv_label_create(ui_MainContainerCompass);
    lv_obj_set_width(ui_LabelCompGPSSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCompGPSSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCompGPSSpeed, 0);
    lv_obj_set_y(ui_LabelCompGPSSpeed, 53);
    lv_obj_set_align(ui_LabelCompGPSSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCompGPSSpeed, "99.9");
    lv_obj_set_style_text_align(ui_LabelCompGPSSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCompGPSSpeed, &ui_font_condensed60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCompDepth = lv_label_create(ui_MainContainerCompass);
    lv_obj_set_width(ui_LabelCompDepth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCompDepth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCompDepth, 0);
    lv_obj_set_y(ui_LabelCompDepth, -20);
    lv_obj_set_align(ui_LabelCompDepth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCompDepth, "99.9");
    lv_obj_set_style_text_align(ui_LabelCompDepth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCompDepth, &ui_font_condensed60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainContainerTridata = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_MainContainerTridata);
    lv_obj_set_width(ui_MainContainerTridata, lv_pct(100));
    lv_obj_set_height(ui_MainContainerTridata, lv_pct(100));
    lv_obj_set_align(ui_MainContainerTridata, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_MainContainerTridata, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainContainerTridata, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainContainerTridata, lv_color_hex(0xD8D8D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainContainerTridata, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNavigation3 = lv_obj_create(ui_MainContainerTridata);
    lv_obj_set_height(ui_PanelNavigation3, 50);
    lv_obj_set_width(ui_PanelNavigation3, lv_pct(100));
    lv_obj_set_align(ui_PanelNavigation3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelNavigation3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNavigation3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNavigation3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelNavigation3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindScreen3 = lv_label_create(ui_PanelNavigation3);
    lv_obj_set_width(ui_LabelWindScreen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindScreen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWindScreen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindScreen3, "Tridata");
    lv_obj_set_style_text_color(ui_LabelWindScreen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindScreen3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_PanelNavigation3);
    lv_obj_set_width(ui_Button7, 80);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, -20);
    lv_obj_set_y(ui_Button7, 0);
    lv_obj_set_align(ui_Button7, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button7, &ui_img_674587949, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_PanelNavigation3);
    lv_obj_set_width(ui_Button4, 80);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 20);
    lv_obj_set_y(ui_Button4, 0);
    lv_obj_set_align(ui_Button4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_1551684850, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_MainContainerTridata);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 430);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 50);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerDirection = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_ContainerDirection);
    lv_obj_set_width(ui_ContainerDirection, lv_pct(100));
    lv_obj_set_height(ui_ContainerDirection, lv_pct(50));
    lv_obj_set_align(ui_ContainerDirection, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerDirection, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerDirection, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerDirection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerDirection, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_ContainerDirection);
    lv_obj_set_width(ui_Panel5, lv_pct(100));
    lv_obj_set_height(ui_Panel5, lv_pct(23));
    lv_obj_set_align(ui_Panel5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Heading (°M)");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_ContainerDirection);
    lv_obj_set_width(ui_Panel6, lv_pct(100));
    lv_obj_set_height(ui_Panel6, lv_pct(77));
    lv_obj_set_align(ui_Panel6, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDirectionValue = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LabelDirectionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDirectionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDirectionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDirectionValue, "000");
    lv_obj_set_style_text_align(ui_LabelDirectionValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDirectionValue, &ui_font_freeman160, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(10));
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 20);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Sensors");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerDepth = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_ContainerDepth);
    lv_obj_set_width(ui_ContainerDepth, lv_pct(50));
    lv_obj_set_height(ui_ContainerDepth, lv_pct(40));
    lv_obj_set_align(ui_ContainerDepth, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_ContainerDepth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerDepth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerDepth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerDepth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_ContainerDepth);
    lv_obj_set_width(ui_Panel8, lv_pct(100));
    lv_obj_set_height(ui_Panel8, lv_pct(23));
    lv_obj_set_align(ui_Panel8, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Depth (m)");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDepthValue = lv_label_create(ui_ContainerDepth);
    lv_obj_set_width(ui_LabelDepthValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDepthValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDepthValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDepthValue, "00.00");
    lv_obj_set_style_text_align(ui_LabelDepthValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDepthValue, &ui_font_freeman60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSpeed = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_ContainerSpeed);
    lv_obj_set_width(ui_ContainerSpeed, lv_pct(50));
    lv_obj_set_height(ui_ContainerSpeed, lv_pct(40));
    lv_obj_set_align(ui_ContainerSpeed, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_ContainerSpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerSpeed, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_ContainerSpeed);
    lv_obj_set_width(ui_Panel9, lv_pct(100));
    lv_obj_set_height(ui_Panel9, lv_pct(23));
    lv_obj_set_align(ui_Panel9, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Speed (kt)");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeedValue = lv_label_create(ui_ContainerSpeed);
    lv_obj_set_width(ui_LabelSpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeedValue, "00.0");
    lv_obj_set_style_text_align(ui_LabelSpeedValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeedValue, &ui_font_freeman60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainContainerStatus = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_MainContainerStatus);
    lv_obj_set_width(ui_MainContainerStatus, lv_pct(100));
    lv_obj_set_height(ui_MainContainerStatus, lv_pct(100));
    lv_obj_set_align(ui_MainContainerStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainContainerStatus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainContainerStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelNavigation4 = lv_obj_create(ui_MainContainerStatus);
    lv_obj_set_height(ui_PanelNavigation4, 50);
    lv_obj_set_width(ui_PanelNavigation4, lv_pct(100));
    lv_obj_set_align(ui_PanelNavigation4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelNavigation4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNavigation4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNavigation4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelNavigation4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindScreen4 = lv_label_create(ui_PanelNavigation4);
    lv_obj_set_width(ui_LabelWindScreen4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindScreen4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWindScreen4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindScreen4, "Status");
    lv_obj_set_style_text_color(ui_LabelWindScreen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindScreen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindScreen4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_PanelNavigation4);
    lv_obj_set_width(ui_Button9, 80);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, -20);
    lv_obj_set_y(ui_Button9, 0);
    lv_obj_set_align(ui_Button9, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button9, &ui_img_674587949, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_MainContainerStatus);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 430);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 30);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 35);
    lv_obj_set_y(ui_Label11, 6);
    lv_label_set_text(ui_Label11, "Device name:");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 116);
    lv_obj_set_y(ui_Label12, 29);
    lv_label_set_text(ui_Label12, "IP:");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownDefaultScreen = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_DropdownDefaultScreen, "Wind\nCompass\nTridata");
    lv_obj_set_width(ui_DropdownDefaultScreen, 170);
    lv_obj_set_height(ui_DropdownDefaultScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownDefaultScreen, 66);
    lv_obj_set_y(ui_DropdownDefaultScreen, -45);
    lv_obj_set_align(ui_DropdownDefaultScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownDefaultScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label16 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 35);
    lv_obj_set_y(ui_Label16, 161);
    lv_label_set_text(ui_Label16, "Default page:");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDeviceName = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelDeviceName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDeviceName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDeviceName, 145);
    lv_obj_set_y(ui_LabelDeviceName, 6);
    lv_label_set_text(ui_LabelDeviceName, "name");
    lv_obj_set_style_text_align(ui_LabelDeviceName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIP = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIP, 145);
    lv_obj_set_y(ui_LabelIP, 29);
    lv_label_set_text(ui_LabelIP, "0.0.0.0");
    lv_obj_set_style_text_align(ui_LabelIP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 51);
    lv_obj_set_y(ui_Label17, 80);
    lv_label_set_text(ui_Label17, "SK address:");
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSKAddress = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelSKAddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSKAddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSKAddress, 145);
    lv_obj_set_y(ui_LabelSKAddress, 80);
    lv_label_set_text(ui_LabelSKAddress, "SK IP:Port");
    lv_obj_set_style_text_align(ui_LabelSKAddress, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 62);
    lv_obj_set_y(ui_Label18, 105);
    lv_label_set_text(ui_Label18, "SK Status:");
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSKStatus = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelSKStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSKStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSKStatus, 148);
    lv_obj_set_y(ui_LabelSKStatus, 105);
    lv_label_set_text(ui_LabelSKStatus, "key needed");
    lv_obj_set_style_text_align(ui_LabelSKStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainContainerSplash = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_MainContainerSplash);
    lv_obj_set_width(ui_MainContainerSplash, lv_pct(100));
    lv_obj_set_height(ui_MainContainerSplash, lv_pct(100));
    lv_obj_set_align(ui_MainContainerSplash, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainContainerSplash, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainContainerSplash, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainContainerSplash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_MainContainerSplash);
    lv_img_set_src(ui_Image1, &ui_img_signalkinstrumentslogo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -140);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_MainContainerSplash, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, -20);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ButtonResetSettings = lv_btn_create(ui_MainContainerSplash);
    lv_obj_set_width(ui_ButtonResetSettings, 200);
    lv_obj_set_height(ui_ButtonResetSettings, 30);
    lv_obj_set_align(ui_ButtonResetSettings, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonResetSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonResetSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonResetSettings, lv_color_hex(0xFF6F6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonResetSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_ButtonResetSettings);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Factory reset");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNeedToConfigure = lv_label_create(ui_MainContainerSplash);
    lv_obj_set_width(ui_LabelNeedToConfigure, lv_pct(100));
    lv_obj_set_height(ui_LabelNeedToConfigure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNeedToConfigure, -1);
    lv_obj_set_y(ui_LabelNeedToConfigure, 67);
    lv_obj_set_align(ui_LabelNeedToConfigure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNeedToConfigure,
                      "Connect to WiFi AP\"Configure asfsfsedfg-sdgsdg-sdgs\" and set WiFi and SignalK connection");
    lv_obj_set_style_text_color(ui_LabelNeedToConfigure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNeedToConfigure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelNeedToConfigure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartWiFiTxt = lv_label_create(ui_MainContainerSplash);
    lv_obj_set_width(ui_LabelStartWiFiTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartWiFiTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartWiFiTxt, 52);
    lv_obj_set_y(ui_LabelStartWiFiTxt, 350);
    lv_label_set_text(ui_LabelStartWiFiTxt, "WiFi:");
    lv_obj_set_style_text_color(ui_LabelStartWiFiTxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartWiFiTxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartWiFiTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartSignalKTxt = lv_label_create(ui_MainContainerSplash);
    lv_obj_set_width(ui_LabelStartSignalKTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartSignalKTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartSignalKTxt, 30);
    lv_obj_set_y(ui_LabelStartSignalKTxt, 398);
    lv_label_set_text(ui_LabelStartSignalKTxt, "SignalK:");
    lv_obj_set_style_text_color(ui_LabelStartSignalKTxt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartSignalKTxt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartSignalKTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartWiFiStatus = lv_label_create(ui_MainContainerSplash);
    lv_obj_set_width(ui_LabelStartWiFiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartWiFiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartWiFiStatus, 100);
    lv_obj_set_y(ui_LabelStartWiFiStatus, 350);
    lv_label_set_text(ui_LabelStartWiFiStatus, "connecting...");
    lv_obj_set_style_text_color(ui_LabelStartWiFiStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartWiFiStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartWiFiStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartSignalK = lv_label_create(ui_MainContainerSplash);
    lv_obj_set_width(ui_LabelStartSignalK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartSignalK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartSignalK, 100);
    lv_obj_set_y(ui_LabelStartSignalK, 396);
    lv_label_set_text(ui_LabelStartSignalK, "connecting...");
    lv_obj_set_style_text_color(ui_LabelStartSignalK, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartSignalK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartSignalK, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStartSignalKStatus = lv_label_create(ui_MainContainerSplash);
    lv_obj_set_width(ui_LabelStartSignalKStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartSignalKStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartSignalKStatus, 100);
    lv_obj_set_y(ui_LabelStartSignalKStatus, 418);
    lv_label_set_text(ui_LabelStartSignalKStatus, "connecting...");
    lv_obj_set_style_text_color(ui_LabelStartSignalKStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStartSignalKStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStartSignalKStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownDefaultScreen, ui_event_DropdownDefaultScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonResetSettings, ui_event_ButtonResetSettings, LV_EVENT_ALL, NULL);

}
