// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: wind_instruments

#include "../ui.h"

void ui_ScreenCompass_screen_init(void)
{
    ui_ScreenCompass = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCompass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_ScreenCompass);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, lv_pct(100));
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCompassNavigation = lv_obj_create(ui_Container2);
    lv_obj_set_height(ui_PanelCompassNavigation, 50);
    lv_obj_set_width(ui_PanelCompassNavigation, lv_pct(100));
    lv_obj_set_align(ui_PanelCompassNavigation, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelCompassNavigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCompassNavigation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCompassNavigation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelCompassNavigation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindScreen2 = lv_label_create(ui_PanelCompassNavigation);
    lv_obj_set_width(ui_LabelWindScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWindScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindScreen2, "Compass");
    lv_obj_set_style_text_color(ui_LabelWindScreen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindScreen2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_PanelCompassNavigation);
    lv_obj_set_width(ui_Button4, 50);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_align(ui_Button4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_674587949, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_PanelCompassNavigation);
    lv_obj_set_width(ui_Button5, 50);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_align(ui_Button5, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button5, &ui_img_1551684850, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCompassMain = lv_obj_create(ui_ScreenCompass);
    lv_obj_remove_style_all(ui_ContainerCompassMain);
    lv_obj_set_width(ui_ContainerCompassMain, 320);
    lv_obj_set_height(ui_ContainerCompassMain, 320);
    lv_obj_set_x(ui_ContainerCompassMain, 0);
    lv_obj_set_y(ui_ContainerCompassMain, 50);
    lv_obj_clear_flag(ui_ContainerCompassMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCompassBack = lv_img_create(ui_ContainerCompassMain);
    lv_img_set_src(ui_ImageCompassBack, &ui_img_827446305);
    lv_obj_set_width(ui_ImageCompassBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCompassBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCompassBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCompassBack, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCompassBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageRedGreen = lv_img_create(ui_ContainerCompassMain);
    lv_img_set_src(ui_ImageRedGreen, &ui_img_1213530082);
    lv_obj_set_width(ui_ImageRedGreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRedGreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageRedGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRedGreen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRedGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageCompassCenter = lv_img_create(ui_ContainerCompassMain);
    lv_img_set_src(ui_ImageCompassCenter, &ui_img_1486399645);
    lv_obj_set_width(ui_ImageCompassCenter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCompassCenter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCompassCenter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageCompassCenter, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCompassCenter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCompasHeading = lv_label_create(ui_ContainerCompassMain);
    lv_obj_set_width(ui_LabelCompasHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCompasHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCompasHeading, 0);
    lv_obj_set_y(ui_LabelCompasHeading, -92);
    lv_obj_set_align(ui_LabelCompasHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCompasHeading, "000");
    lv_obj_set_style_text_align(ui_LabelCompasHeading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCompasHeading, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_ContainerCompassMain);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -59);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Depth (m)");

    ui_Label10 = lv_label_create(ui_ContainerCompassMain);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 15);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "GPS speed (kt)");

    ui_LabelCompGPSSpeed = lv_label_create(ui_ContainerCompassMain);
    lv_obj_set_width(ui_LabelCompGPSSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCompGPSSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCompGPSSpeed, 0);
    lv_obj_set_y(ui_LabelCompGPSSpeed, 53);
    lv_obj_set_align(ui_LabelCompGPSSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCompGPSSpeed, "99.9");
    lv_obj_set_style_text_align(ui_LabelCompGPSSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCompGPSSpeed, &ui_font_condensed60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCompDepth = lv_label_create(ui_ContainerCompassMain);
    lv_obj_set_width(ui_LabelCompDepth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCompDepth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCompDepth, 0);
    lv_obj_set_y(ui_LabelCompDepth, -20);
    lv_obj_set_align(ui_LabelCompDepth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCompDepth, "99.9");
    lv_obj_set_style_text_align(ui_LabelCompDepth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCompDepth, &ui_font_condensed60, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}
