// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: wind_instruments

#include "../ui.h"

void ui_ScreenWind_screen_init(void)
{
    ui_ScreenWind = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWind = lv_obj_create(ui_ScreenWind);
    lv_obj_remove_style_all(ui_ContainerWind);
    lv_obj_set_width(ui_ContainerWind, lv_pct(100));
    lv_obj_set_height(ui_ContainerWind, lv_pct(100));
    lv_obj_set_align(ui_ContainerWind, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWind, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerWind, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerWind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWindNavigation = lv_obj_create(ui_ContainerWind);
    lv_obj_set_height(ui_PanelWindNavigation, 50);
    lv_obj_set_width(ui_PanelWindNavigation, lv_pct(100));
    lv_obj_set_align(ui_PanelWindNavigation, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelWindNavigation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWindNavigation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWindNavigation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWindNavigation, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindScreen = lv_label_create(ui_PanelWindNavigation);
    lv_obj_set_width(ui_LabelWindScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWindScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWindScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindScreen, "Wind");
    lv_obj_set_style_text_color(ui_LabelWindScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWindScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWindScreen, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_PanelWindNavigation);
    lv_obj_set_width(ui_Button2, 50);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_align(ui_Button2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button2, &ui_img_674587949, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_PanelWindNavigation);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_align(ui_Button3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_1551684850, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWindGauge = lv_obj_create(ui_ContainerWind);
    lv_obj_set_width(ui_PanelWindGauge, 320);
    lv_obj_set_height(ui_PanelWindGauge, 320);
    lv_obj_set_x(ui_PanelWindGauge, 0);
    lv_obj_set_y(ui_PanelWindGauge, 50);
    lv_obj_clear_flag(ui_PanelWindGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWindGauge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWindGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWindGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PanelWindGauge, &ui_img_scale_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWindGauge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAppWindSpd = lv_label_create(ui_PanelWindGauge);
    lv_obj_set_width(ui_LabelAppWindSpd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAppWindSpd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAppWindSpd, -9);
    lv_obj_set_y(ui_LabelAppWindSpd, 68);
    lv_obj_set_align(ui_LabelAppWindSpd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAppWindSpd, "00.0");
    lv_obj_set_style_text_color(ui_LabelAppWindSpd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAppWindSpd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAppWindSpd, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAppWindSpd, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArrowTrue = lv_img_create(ui_PanelWindGauge);
    lv_img_set_src(ui_ImageArrowTrue, &ui_img_arrow_true_png);
    lv_obj_set_width(ui_ImageArrowTrue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArrowTrue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageArrowTrue, 0);
    lv_obj_set_y(ui_ImageArrowTrue, -130);
    lv_obj_set_align(ui_ImageArrowTrue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageArrowTrue, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageArrowTrue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageArrowTrue, 8, 148);
    lv_img_set_angle(ui_ImageArrowTrue, 1270);

    ui_ImageArrowApp = lv_img_create(ui_PanelWindGauge);
    lv_img_set_src(ui_ImageArrowApp, &ui_img_arrow_app_png);
    lv_obj_set_width(ui_ImageArrowApp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArrowApp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageArrowApp, 0);
    lv_obj_set_y(ui_ImageArrowApp, -80);
    lv_obj_set_align(ui_ImageArrowApp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageArrowApp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageArrowApp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_ImageArrowApp, 8, 123);
    lv_img_set_angle(ui_ImageArrowApp, 2700);

    ui_ContainerTWS = lv_obj_create(ui_ScreenWind);
    lv_obj_remove_style_all(ui_ContainerTWS);
    lv_obj_set_width(ui_ContainerTWS, 121);
    lv_obj_set_height(ui_ContainerTWS, 64);
    lv_obj_set_x(ui_ContainerTWS, 8);
    lv_obj_set_y(ui_ContainerTWS, 345);
    lv_obj_clear_flag(ui_ContainerTWS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1TWS = lv_label_create(ui_ContainerTWS);
    lv_obj_set_width(ui_Label1TWS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1TWS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1TWS, 10);
    lv_obj_set_y(ui_Label1TWS, 0);
    lv_label_set_text(ui_Label1TWS, "TWS");
    lv_obj_set_style_text_color(ui_Label1TWS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1TWS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1TWS, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_ContainerTWS);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 2);
    lv_obj_set_x(ui_Panel1, 10);
    lv_obj_set_y(ui_Panel1, 25);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWSValue = lv_label_create(ui_ContainerTWS);
    lv_obj_set_width(ui_LabelTWSValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWSValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWSValue, -35);
    lv_obj_set_y(ui_LabelTWSValue, 15);
    lv_obj_set_align(ui_LabelTWSValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTWSValue, "00.0");
    lv_obj_set_style_text_color(ui_LabelTWSValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWSValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWSValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ContainerTWS);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 43);
    lv_obj_set_y(ui_Label2, 18);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "k\nt");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTWA = lv_obj_create(ui_ScreenWind);
    lv_obj_remove_style_all(ui_ContainerTWA);
    lv_obj_set_width(ui_ContainerTWA, 121);
    lv_obj_set_height(ui_ContainerTWA, 64);
    lv_obj_set_x(ui_ContainerTWA, 196);
    lv_obj_set_y(ui_ContainerTWA, 413);
    lv_obj_clear_flag(ui_ContainerTWA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1TWA = lv_label_create(ui_ContainerTWA);
    lv_obj_set_width(ui_Label1TWA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1TWA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1TWA, 16);
    lv_obj_set_y(ui_Label1TWA, 4);
    lv_label_set_text(ui_Label1TWA, "TWA");
    lv_obj_set_style_text_color(ui_Label1TWA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1TWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1TWA, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label1TWA, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1TWA, lv_color_hex(0xFFFD18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1TWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label1TWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1TWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1TWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1TWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_ContainerTWA);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 2);
    lv_obj_set_x(ui_Panel2, 10);
    lv_obj_set_y(ui_Panel2, 33);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWAValue = lv_label_create(ui_ContainerTWA);
    lv_obj_set_width(ui_LabelTWAValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWAValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWAValue, -35);
    lv_obj_set_y(ui_LabelTWAValue, 17);
    lv_obj_set_align(ui_LabelTWAValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTWAValue, "000");
    lv_obj_set_style_text_color(ui_LabelTWAValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWAValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWAValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ContainerTWA);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 34);
    lv_obj_set_y(ui_Label1, 6);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "o");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerAWA = lv_obj_create(ui_ScreenWind);
    lv_obj_remove_style_all(ui_ContainerAWA);
    lv_obj_set_width(ui_ContainerAWA, 121);
    lv_obj_set_height(ui_ContainerAWA, 64);
    lv_obj_set_x(ui_ContainerAWA, 8);
    lv_obj_set_y(ui_ContainerAWA, 413);
    lv_obj_clear_flag(ui_ContainerAWA, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAWA = lv_label_create(ui_ContainerAWA);
    lv_obj_set_width(ui_LabelAWA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAWA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAWA, 16);
    lv_obj_set_y(ui_LabelAWA, 4);
    lv_label_set_text(ui_LabelAWA, "AWA");
    lv_obj_set_style_text_color(ui_LabelAWA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAWA, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelAWA, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelAWA, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelAWA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelAWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelAWA, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelAWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelAWA, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ContainerAWA);
    lv_obj_set_width(ui_Panel3, 100);
    lv_obj_set_height(ui_Panel3, 2);
    lv_obj_set_x(ui_Panel3, 10);
    lv_obj_set_y(ui_Panel3, 33);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAWAValue = lv_label_create(ui_ContainerAWA);
    lv_obj_set_width(ui_LabelAWAValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAWAValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAWAValue, -35);
    lv_obj_set_y(ui_LabelAWAValue, 17);
    lv_obj_set_align(ui_LabelAWAValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelAWAValue, "000");
    lv_obj_set_style_text_color(ui_LabelAWAValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAWAValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAWAValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ContainerAWA);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 34);
    lv_obj_set_y(ui_Label3, 6);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "o");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerTWD = lv_obj_create(ui_ScreenWind);
    lv_obj_remove_style_all(ui_ContainerTWD);
    lv_obj_set_width(ui_ContainerTWD, 121);
    lv_obj_set_height(ui_ContainerTWD, 64);
    lv_obj_set_x(ui_ContainerTWD, 196);
    lv_obj_set_y(ui_ContainerTWD, 345);
    lv_obj_clear_flag(ui_ContainerTWD, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWD = lv_label_create(ui_ContainerTWD);
    lv_obj_set_width(ui_LabelTWD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWD, -14);
    lv_obj_set_y(ui_LabelTWD, 0);
    lv_obj_set_align(ui_LabelTWD, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTWD, "TWD");
    lv_obj_set_style_text_color(ui_LabelTWD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWD, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_ContainerTWD);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 2);
    lv_obj_set_x(ui_Panel4, 10);
    lv_obj_set_y(ui_Panel4, 25);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTWDValue = lv_label_create(ui_ContainerTWD);
    lv_obj_set_width(ui_LabelTWDValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTWDValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTWDValue, -35);
    lv_obj_set_y(ui_LabelTWDValue, 15);
    lv_obj_set_align(ui_LabelTWDValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelTWDValue, "000");
    lv_obj_set_style_text_color(ui_LabelTWDValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTWDValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTWDValue, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ContainerTWD);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 34);
    lv_obj_set_y(ui_Label4, 6);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "o");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
